import type { Locale } from './types';

export const TEXT = {
  fr: {
    topTag: 'Analyse chronobiologie · horaires atypiques',
    steps: ['Profil', 'Travail', 'Sommeil', 'Resultats'],
    progress: 'Progression du test',
    helper:
      'Le parcours est decoupe pour eviter la grosse page indigeste. Tu peux avancer etape par etape.',
    home: 'Accueil',
    analyze: 'Analyse',
    method: 'Methode',
    study: 'Etude',
    consent: 'Consentement',
    legal: 'Legal',
    about: 'A propos',
    previous: 'Precedent',
    next: 'Suivant',
    finish: 'Voir les resultats',
    required: 'Complete les champs requis pour continuer.',
    profileTitle: 'Profil participant',
    profileSubtitle:
      'Version courte ou longue. Le mode long ajoute quelques variables utiles pour la recherche.',
    modeShort: 'Mode court',
    modeLong: 'Mode long',
    profession: 'Metier',
    professionPlaceholder: 'Ex: Infirmier, securite, logistique...',
    ageBand: "Tranche d'age",
    sex: 'Sexe (optionnel)',
    chronotype: 'Chronotype (optionnel mais utile)',
    fatigue: 'Fatigue percue (1-5)',
    predictability: 'Previsibilite du planning (1-5)',
    commute: 'Trajet (minutes)',
    naps: 'Siestes / semaine',
    caffeine: 'Cafes / jour',
    scoringReady: 'Relie au scoring',
    scoringLater: 'Coming soon',
    longModeNotice:
      'Ces champs enrichissent deja la collecte de recherche, mais ils ne sont pas encore relies au moteur de scoring v0.1.',
    select: 'Choisir...',
    ages: ['18-24', '25-34', '35-44', '45-54', '55-64', '65+'],
    sexes: [
      ['female', 'Femme'],
      ['male', 'Homme'],
      ['other', 'Autre'],
      ['prefer_not_to_say', 'Prefere ne pas dire'],
    ] as const,
    chronotypes: [
      ['morning', 'Matinal'],
      ['intermediate', 'Intermediaire'],
      ['evening', 'Vesperal'],
    ] as const,
    workTitle: 'Agenda de travail (1 semaine)',
    sleepTitle: 'Agenda de sommeil (1 semaine)',
    calendarSubtitle:
      'Clique dans la grille pour preremplir un segment, puis ajuste si besoin. Le rendu est style agenda hebdomadaire.',
    day: 'Jour',
    start: 'Debut',
    end: 'Fin',
    overnight: 'Passe minuit',
    addSegment: 'Ajouter segment',
    updateSegment: 'Mettre a jour',
    resetDraft: 'Reinit draft',
    noSegments: 'Aucun segment pour le moment.',
    quickTips:
      'Conseil: pour une nuit 22:00 -> 06:00, coche "Passe minuit" (ou mets fin < debut, ca s active auto).',
    workLegend: 'Bloc de travail',
    sleepLegend: 'Bloc de sommeil',
    segments: 'Segments',
    edit: 'Editer',
    delete: 'Supprimer',
    duplicate: 'Dupliquer',
    resultsTitle: 'Resultats & contribution',
    resultsSubtitle:
      'Scores calcules localement. Contribution a l etude separee (opt-in) et non requise pour voir le resultat.',
    scoreRisk: 'Risque',
    scoreSleep: 'Sommeil',
    scoreAdapt: 'Adaptabilite',
    riskHint: 'Plus haut = plus de contraintes/risque',
    sleepHint: 'Plus haut = meilleur sommeil (proxy)',
    adaptHint: 'Score principal (proxy v0.1)',
    derived: 'Metriques derivees',
    explanations: 'Lecture rapide',
    contribution: "Contribuer a l'etude",
    endpoint: 'Endpoint collecte (optionnel)',
    endpointPlaceholder: 'https://... (Google Apps Script, webhook, etc.)',
    consentCheck:
      "J'accepte de contribuer mes donnees a l'etude (consentement explicite).",
    anonId: 'Inclure un identifiant anonyme local',
    sendData: 'Envoyer',
    sentOk: 'Envoi OK',
    sentError: 'Echec envoi',
    copyJson: 'Copier JSON',
    exportJson: 'Telecharger JSON',
    resetAll: 'Tout reinitialiser',
    notMedical: 'Outil de recherche / pre-analyse. Ne remplace pas un avis medical.',
    saveVersion: 'Version scoring',
    shortModeBlock: 'Mode court: variables minimales pour MVP.',
    longModeBlock:
      'Mode long: ajoute fatigue / planning / trajet / siestes / cafeine.',
    daysShort: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'],
    scoreScaleLow: 'Faible',
    scoreScaleHigh: 'Eleve',
  },
  en: {
    topTag: 'Chronobiology analysis · shift work',
    steps: ['Profile', 'Work', 'Sleep', 'Results'],
    progress: 'Test progress',
    helper:
      'The flow is split into steps so it feels lighter. Complete one step at a time.',
    home: 'Home',
    analyze: 'Analyze',
    method: 'Method',
    study: 'Study',
    consent: 'Consent',
    legal: 'Legal',
    about: 'About',
    previous: 'Previous',
    next: 'Next',
    finish: 'See results',
    required: 'Complete required fields to continue.',
    profileTitle: 'Participant profile',
    profileSubtitle:
      'Short or long version. Long mode adds variables useful for research.',
    modeShort: 'Short mode',
    modeLong: 'Long mode',
    profession: 'Profession',
    professionPlaceholder: 'e.g. Nurse, security, logistics...',
    ageBand: 'Age band',
    sex: 'Sex (optional)',
    chronotype: 'Chronotype (optional but useful)',
    fatigue: 'Perceived fatigue (1-5)',
    predictability: 'Schedule predictability (1-5)',
    commute: 'Commute (minutes)',
    naps: 'Naps / week',
    caffeine: 'Cups of coffee / day',
    scoringReady: 'Connected to scoring',
    scoringLater: 'Coming soon',
    longModeNotice:
      'These fields already enrich the research dataset, but they are not yet connected to scoring v0.1.',
    select: 'Choose...',
    ages: ['18-24', '25-34', '35-44', '45-54', '55-64', '65+'],
    sexes: [
      ['female', 'Female'],
      ['male', 'Male'],
      ['other', 'Other'],
      ['prefer_not_to_say', 'Prefer not to say'],
    ] as const,
    chronotypes: [
      ['morning', 'Morning'],
      ['intermediate', 'Intermediate'],
      ['evening', 'Evening'],
    ] as const,
    workTitle: 'Work schedule (1 week)',
    sleepTitle: 'Sleep schedule (1 week)',
    calendarSubtitle:
      'Click inside the grid to prefill a segment, then adjust if needed. Weekly agenda style.',
    day: 'Day',
    start: 'Start',
    end: 'End',
    overnight: 'Crosses midnight',
    addSegment: 'Add segment',
    updateSegment: 'Update',
    resetDraft: 'Reset draft',
    noSegments: 'No segment yet.',
    quickTips:
      'Tip: for a 22:00 -> 06:00 night, tick "Crosses midnight" (or set end < start).',
    workLegend: 'Work block',
    sleepLegend: 'Sleep block',
    segments: 'Segments',
    edit: 'Edit',
    delete: 'Delete',
    duplicate: 'Duplicate',
    resultsTitle: 'Results & contribution',
    resultsSubtitle:
      'Scores are computed locally. Study contribution is separate (opt-in) and not required.',
    scoreRisk: 'Risk',
    scoreSleep: 'Sleep',
    scoreAdapt: 'Adaptability',
    riskHint: 'Higher = more constraints/risk',
    sleepHint: 'Higher = better sleep (proxy)',
    adaptHint: 'Main score (proxy v0.1)',
    derived: 'Derived metrics',
    explanations: 'Quick reading',
    contribution: 'Contribute to the study',
    endpoint: 'Collection endpoint (optional)',
    endpointPlaceholder: 'https://... (Google Apps Script, webhook, etc.)',
    consentCheck:
      'I agree to contribute my data to the study (explicit consent).',
    anonId: 'Include local anonymous ID',
    sendData: 'Send',
    sentOk: 'Sent',
    sentError: 'Send failed',
    copyJson: 'Copy JSON',
    exportJson: 'Download JSON',
    resetAll: 'Reset all',
    notMedical: 'Research / pre-analysis tool. Not medical advice.',
    saveVersion: 'Scoring version',
    shortModeBlock: 'Short mode: minimal variables for MVP.',
    longModeBlock:
      'Long mode: adds fatigue / schedule / commute / naps / caffeine.',
    daysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    scoreScaleLow: 'Low',
    scoreScaleHigh: 'High',
  },
  de: {
    topTag: 'Chronobiologie-Analyse · Schichtarbeit',
    steps: ['Profil', 'Arbeit', 'Schlaf', 'Ergebnisse'],
    progress: 'Testfortschritt',
    helper:
      'Der Ablauf ist in Schritte geteilt, damit es leichter wirkt. Schritt fur Schritt ausfullen.',
    home: 'Home',
    analyze: 'Analyse',
    method: 'Methodik',
    study: 'Studie',
    consent: 'Einwilligung',
    legal: 'Rechtliches',
    about: 'Uber',
    previous: 'Zuruck',
    next: 'Weiter',
    finish: 'Ergebnisse sehen',
    required: 'Bitte Pflichtfelder ausfullen.',
    profileTitle: 'Teilnehmerprofil',
    profileSubtitle:
      'Kurze oder lange Version. Der Langmodus erganzt nutzliche Forschungsvariablen.',
    modeShort: 'Kurzmodus',
    modeLong: 'Langmodus',
    profession: 'Beruf',
    professionPlaceholder: 'z. B. Pflege, Sicherheit, Logistik...',
    ageBand: 'Altersgruppe',
    sex: 'Geschlecht (optional)',
    chronotype: 'Chronotyp (optional, aber nutzlich)',
    fatigue: 'Wahrgenommene Mudigkeit (1-5)',
    predictability: 'Vorhersehbarkeit des Plans (1-5)',
    commute: 'Arbeitsweg (Minuten)',
    naps: 'Nickerchen / Woche',
    caffeine: 'Kaffee / Tag',
    scoringReady: 'Mit Scoring verbunden',
    scoringLater: 'Coming soon',
    longModeNotice:
      'Diese Felder bereichern bereits den Forschungsdatensatz, sind aber noch nicht mit dem Scoring v0.1 verbunden.',
    select: 'Auswahlen...',
    ages: ['18-24', '25-34', '35-44', '45-54', '55-64', '65+'],
    sexes: [
      ['female', 'Weiblich'],
      ['male', 'Mannlich'],
      ['other', 'Andere'],
      ['prefer_not_to_say', 'Keine Angabe'],
    ] as const,
    chronotypes: [
      ['morning', 'Fruh'],
      ['intermediate', 'Mittel'],
      ['evening', 'Spat'],
    ] as const,
    workTitle: 'Arbeitsplan (1 Woche)',
    sleepTitle: 'Schlafplan (1 Woche)',
    calendarSubtitle:
      'In die Rasteransicht klicken, um ein Segment vorzubelegen. Wochenagenda-Stil.',
    day: 'Tag',
    start: 'Start',
    end: 'Ende',
    overnight: 'Uber Mitternacht',
    addSegment: 'Segment hinzufugen',
    updateSegment: 'Aktualisieren',
    resetDraft: 'Entwurf reset',
    noSegments: 'Noch kein Segment.',
    quickTips:
      'Tipp: Fur 22:00 -> 06:00 "Uber Mitternacht" aktivieren (oder Ende < Start setzen).',
    workLegend: 'Arbeitsblock',
    sleepLegend: 'Schlafblock',
    segments: 'Segmente',
    edit: 'Bearbeiten',
    delete: 'Loschen',
    duplicate: 'Duplizieren',
    resultsTitle: 'Ergebnisse & Beitrag',
    resultsSubtitle:
      'Scores werden lokal berechnet. Studienbeitrag ist getrennt (Opt-in) und nicht erforderlich.',
    scoreRisk: 'Risiko',
    scoreSleep: 'Schlaf',
    scoreAdapt: 'Anpassung',
    riskHint: 'Hoher = mehr Belastung/Risiko',
    sleepHint: 'Hoher = besserer Schlaf (Proxy)',
    adaptHint: 'Hauptscore (Proxy v0.1)',
    derived: 'Abgeleitete Metriken',
    explanations: 'Kurzinterpretation',
    contribution: 'Zur Studie beitragen',
    endpoint: 'Erhebungs-Endpoint (optional)',
    endpointPlaceholder: 'https://... (Google Apps Script, Webhook, etc.)',
    consentCheck:
      'Ich stimme zu, meine Daten der Studie beizutragen (ausdruckliche Einwilligung).',
    anonId: 'Lokale anonyme ID mitsenden',
    sendData: 'Senden',
    sentOk: 'Gesendet',
    sentError: 'Senden fehlgeschlagen',
    copyJson: 'JSON kopieren',
    exportJson: 'JSON herunterladen',
    resetAll: 'Alles zurucksetzen',
    notMedical: 'Forschungs-/Voranalyse-Tool. Keine medizinische Beratung.',
    saveVersion: 'Scoring-Version',
    shortModeBlock: 'Kurzmodus: minimale Variablen fur MVP.',
    longModeBlock:
      'Langmodus: erganzt Mudigkeit / Plan / Arbeitsweg / Nickerchen / Kaffee.',
    daysShort: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
    scoreScaleLow: 'Niedrig',
    scoreScaleHigh: 'Hoch',
  },
} as const;

export type AnalyzeText = (typeof TEXT)[Locale];

export function isLocale(v: string): v is Locale {
  return v === 'fr' || v === 'en' || v === 'de';
}
